packages:
  - apps/**
  - packages/**
  - services/**
  - '!**/test/**'

catalog:
  '@better-auth/passkey': ^1.4.17
  '@biomejs/biome': 2.3.12
  '@catppuccin/tailwindcss': ^1.0.0
  '@dnd-kit/core': ^6.3.1
  '@dnd-kit/modifiers': ^9.0.0
  '@dnd-kit/sortable': ^10.0.0
  '@dnd-kit/utilities': ^3.2.2
  '@hono/node-server': ^1.19.9
  '@hono/standard-validator': ^0.2.2
  '@radix-ui/react-accordion': ^1.2.12
  '@radix-ui/react-alert-dialog': ^1.1.15
  '@radix-ui/react-aspect-ratio': ^1.1.8
  '@radix-ui/react-avatar': ^1.1.11
  '@radix-ui/react-checkbox': ^1.3.3
  '@radix-ui/react-collapsible': ^1.1.12
  '@radix-ui/react-context-menu': ^2.2.16
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-hover-card': ^1.1.15
  '@radix-ui/react-label': ^2.1.8
  '@radix-ui/react-menubar': ^1.1.16
  '@radix-ui/react-navigation-menu': ^1.2.14
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-progress': ^1.1.8
  '@radix-ui/react-radio-group': ^1.3.8
  '@radix-ui/react-scroll-area': ^1.2.10
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-separator': ^1.1.8
  '@radix-ui/react-slider': ^1.3.6
  '@radix-ui/react-slot': 1.2.4
  '@radix-ui/react-switch': ^1.2.6
  '@radix-ui/react-tabs': ^1.1.13
  '@radix-ui/react-toggle': ^1.1.10
  '@radix-ui/react-toggle-group': ^1.1.11
  '@radix-ui/react-tooltip': ^1.2.8
  '@radix-ui/react-use-controllable-state': ^1.2.2
  '@react-three/drei': ^10.7.7
  '@react-three/fiber': 10.0.0-alpha.2
  '@shikijs/transformers': ^3.21.0
  '@tailwindcss/postcss': ^4.1.18
  '@tanstack/react-form': ^1.28.0
  '@tsparticles/engine': ^3.9.1
  '@tsparticles/react': ^3.0.0
  '@tsparticles/slim': ^3.9.1
  '@types/culori': ^4.0.1
  '@types/fs-extra': ^11.0.4
  '@types/lodash.throttle': ^4.1.9
  '@types/node': 25.0.10
  '@types/nodemailer': ^7.0.5
  '@types/pg': ^8.16.0
  '@types/qrcode': ^1.5.6
  '@types/react': ^19
  '@types/react-dom': ^19.2.3
  '@types/react-syntax-highlighter': ^15.5.13
  '@types/tailwindcss': ^3.1.0
  '@uidotdev/usehooks': ^2.4.1
  bcryptjs: ^3.0.3
  better-auth: ^1.4.17
  class-variance-authority: 0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  color: ^5.0.3
  color-convert: ^3.1.3
  cross-env: ^10.1.0
  culori: ^4.0.2
  date-fns: ^4.1.0
  dotenv: ^17.2.3
  dotenv-mono: ^1.5.1
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  embla-carousel-react: ^8.6.0
  execa: ^9.6.1
  fs-extra: ^11.3.3
  hono: ^4.11.5
  hono-openapi: ^1.1.2
  hono-rate-limiter: ^0.5.3
  input-otp: ^1.4.2
  jotai: ^2.16.2
  lefthook: ^2.0.15
  lodash.throttle: ^4.1.1
  lucide-react: 0.563.0
  magic-string: ^0.30.21
  motion: ^12.29.0
  next: 16.1.4
  next-themes: ^0.4.6
  nodemailer: ^7.0.12
  npm-run-path: ^6.0.0
  pathe: ^2.0.3
  pg: ^8.17.2
  postcss: ^8.5.6
  qrcode: ^1.5.4
  radix-ui: ^1.4.3
  react: 19.2.3
  react-day-picker: ^9.13.0
  react-dom: 19.2.3
  react-icons: ^5.5.0
  react-resizable-panels: ^4.5.2
  react-syntax-highlighter: ^16.1.0
  recharts: 3.7.0
  shadcn: ^3.7.0
  shiki: ^3.21.0
  simplex-noise: ^4.0.3
  sonner: ^2.0.7
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  three: ^0.182.0
  three-globe: ^2.45.0
  tsx: ^4.21.0
  tunnel-rat: ^0.1.2
  turbo: ^2.7.6
  tw-animate-css: ^1.4.0
  typescript: ~5.9.3
  ultracite: 7.0.12
  unicorn-magic: 0.4.0
  uuid: ^13.0.0
  vaul: ^1.1.2
  zod: ^4.3.6

cleanupUnusedCatalogs: true

configDependencies:
  '@pnpm/plugin-types-fixer': 0.1.0+sha512-bLww63gRHi7siYTqFJb5qNdcXadU0jv20Et6z5AryMZ7FlLolbEJOrXLpg8+amQZNHHNW1dfFUBGVw/9ezQbFg==

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@sentry-internal/node-cpu-profiler'
  - '@sentry/cli'
  - '@tsparticles/engine'
  - core-js
  - esbuild
  - lefthook
  - msw
  - sharp

preferWorkspacePackages: true
