packages:
  - apps/**
  - packages/**
  - services/**
  - '!**/test/**'

catalog:
  '@biomejs/biome': 2.3.11
  '@hono/node-server': ^1.19.9
  '@hono/standard-validator': ^0.2.2
  '@radix-ui/react-slot': 1.2.4
  '@tailwindcss/postcss': ^4.1.18
  '@types/node': ^24.10.9
  '@types/react': ^19
  '@types/react-dom': ^19.2.3
  class-variance-authority: 0.7.1
  clsx: ^2.1.1
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  hono: ^4.11.4
  hono-openapi: ^1.1.2
  hono-rate-limiter: ^0.5.3
  lefthook: ^2.0.15
  lucide-react: 0.563.0
  next: 16.1.4
  pg: ^8.17.2
  postcss: ^8.5.6
  react: 19.2.3
  react-dom: 19.2.3
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tsx: ^4.21.0
  turbo: ^2.7.5
  tw-animate-css: ^1.4.0
  typescript: ~5.9.3
  ultracite: 7.0.12
  zod: ^4.3.5

configDependencies:
  '@pnpm/plugin-types-fixer': 0.1.0+sha512-bLww63gRHi7siYTqFJb5qNdcXadU0jv20Et6z5AryMZ7FlLolbEJOrXLpg8+amQZNHHNW1dfFUBGVw/9ezQbFg==

onlyBuiltDependencies:
  - '@tsparticles/engine'
  - esbuild
  - lefthook
  - msw
  - sharp
