import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@foundry/ui/global.css";
import "@foundry/ui/shadcn.css";
import "@foundry/ui/catppuccin.css";
import { SidebarInset, SidebarProvider } from "@foundry/ui/primitives/sidebar";
import { Toaster } from "@foundry/ui/primitives/sonner";
import { AppSidebar } from "../components/app-sidebar";
import { ThemeProvider } from "../providers/next-theme-provider";
import { CustomThemeProvider } from "../providers/theme-provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ThemeProvider attribute="class" defaultTheme="system" disableTransitionOnChange enableSystem>
                    <CustomThemeProvider>
                        <SidebarProvider>
                            <AppSidebar />
                            <SidebarInset>{children}</SidebarInset>
                        </SidebarProvider>
                        <Toaster />
                    </CustomThemeProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
