export {};

// Ensure the forum OAuth client is registered (useful in local/dev without running DB migrations).
// This is idempotent — the server-side API will reject duplicates and the call is wrapped in a guard.
/*try {
        const client = await auth.api.registerOAuthApplication({
            body: {
                redirect_uris: [
                    "https://forum.homestead.systems/auth/oidc/callback",
                    "https://forum.homestead.systems/auth/oauth2_basic/callback",
                    "https://foundry.homestead.systems/auth/oidc/callback",
                ],
                token_endpoint_auth_method: "none", // public PKCE client
                grant_types: ["authorization_code", "refresh_token"],
                response_types: ["code"],
                client_name: "Foundry Forum",
                scope: "openid profile email offline_access",
                contacts: ["admin@homestead.systems"],
                metadata: { autogenerated: true },
            },
        });
        console.log("Registered forum OAuth client:", client);
} catch (err) {
    // don't block startup — log for troubleshooting
    // eslint-disable-next-line no-console
    console.error("forum oauth client registration failed:", err);
}*/
